### PR TITLE
chore(dependencies): Update dependencies

### PR DESCRIPTION
**Pull request by jnv**
Blocked on https://github.com/facebook/docusaurus/issues/5863

### CODE REVIEW

**Comment by jnv** [comment]
Keeping in draft until the new release of Docusaurus.

**Comment by jnv** [comment]
This got a bit stale, I've updated it with new dependencies.

**Comment by jnv** [comment]
Nevermind, looks like there's some issue with MDX...

**Review by kysely — APPROVED** [review]
👍

**Pull request merged**
